In [1]:
# Python program to demonstrate
# indexing in numpy array
import numpy as np
 
# Initial Array
arr = np.array(
    [
                [-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]
    ]
    )
print("Initial Array: ")
print(arr)
 
# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[:-1, ::2]
print ("Array with first 3 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)
 
# Printing elements at
# specific Indices
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)


Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 3 rows and alternate columns(0 and 2):
 [[-1.   0. ]
 [ 4.   6. ]
 [ 2.6  7. ]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [2]:
# Python program to demonstrate
# basic operations on single array
import numpy as np
 
# Defining Array 1
a = np.array(
    [
              [1, 2],
              [3, 4]
    ]
)
 
# Defining Array 2
b = np.array(
    [
              [4, 3],
              [2, 1]
    ]
)
               
# Adding 1 to every element
a=a + 1
print ("Adding 1 to every element:", a)
 
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)
print ("\nArray subtract:\n", a - b)
print ("\nMultiplication:\n", np.multiply(a,b))
print ("\nMultiplication:\n", a*b)
print ("\nMatrix Multiplication:\n", np.matmul(a,b))
print ("\nInverse of matrix a:\n", np.linalg.inv(a))
print ("\nTranspose :\n", a.transpose())


Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  14

Array sum:
 [[6 6]
 [6 6]]

Array subtract:
 [[-2  0]
 [ 2  4]]

Multiplication:
 [[8 9]
 [8 5]]

Multiplication:
 [[8 9]
 [8 5]]

Matrix Multiplication:
 [[14  9]
 [26 17]]

Inverse of matrix a:
 [[-2.5  1.5]
 [ 2.  -1. ]]

Transpose :
 [[2 4]
 [3 5]]


In [3]:
# Python Program to create
# a data type object
import numpy as np
 
# Integer datatype
# guessed by Numpy
x = np.array(
        [
            [240000000,10,11],
            [5454545455454,10,10]
        ]
        )
        
print("Integer Datatype: ")
print(x)
print(x.dtype)         
 
# Float datatype
# guessed by Numpy
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  
 
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)


Integer Datatype: 
[[    240000000            10            11]
 [5454545455454            10            10]]
int64

Float Datatype: 
float64

Forcing a Datatype: 
int64
